version: "3.9"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_DB: people_db
      POSTGRES_USER: people
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgres/data
  people_app:
    container_name: people_app
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST_NAME: postgres
    depends_on:
      - postgres

volumes:
  postgres_volume: